- name: Ensure group node-exporter exists
  ansible.builtin.group:
    name: '{{ node_exporter_group }}'
    state: present
  become: yes

- name: add node-exporter user
  user:
    name: '{{ node_exporter_user }}'
    shell: /usr/sbin/nologin
    group: '{{ node_exporter_group }}'
    system: true
  become: yes


