nginx_vhosts:
  - listen: "80"
    server_name: "{{domain_name}} www.{{domain_name}}"
    return: "301 https://{{domain_name}}$request_uri"
    filename: "{{domain_name}}.80.conf"

  - listen: "443 ssl http2"
    server_name: "{{domain_name}}"
    server_name_redirect: "www.{{domain_name}}"
    root: "{{root}}"
    index: "index.php index.html index.htm"
    error_page: ""
    access_log: "/var/log/nginx/{{domain_log}}_access_json.log  mainJSON"
    error_log: "/var/log/nginx/{{domain_log}}_error_json.log"
    state: "present"
    template: "{{ nginx_vhost_template }}"
    filename: "domain_name.conf"
    extra_parameters: |
      include include.d/ssl-options.conf;
      include /etc/nginx/include.d/proxy-options.conf;
      ssl_certificate     /etc/ssl/{{domain_name}}/fullchain.pem;
      ssl_certificate_key /etc/ssl/{{domain_name}}/privkey.key;
      ssl_protocols       TLSv1.1 TLSv1.2;
      ssl_ciphers         HIGH:!aNULL:!MD5;
